### url mappings ###

class URLMappings(dict):
    def __missing__(self, x):
        return self['http://localhost:8080']


new_or_old = URLMappings({'http://amsterdam.the-hub.net':'new',
                          'http://bayarea.the-hub.net':'new',
                          'http://berlin.the-hub.net':'new',
                          'http://berkeley.the-hub.net':'new',
                          'http://bombay.the-hub.net':'new',
                          'http://bristol.the-hub.net':'new',
                          'http://brussels.the-hub.net':'new',
                          'http://cairo.the-hub.net':'new',
                          'http://halifax.the-hub.net':'new',
                          'http://islington.the-hub.net':'new',
                          'http://johannesburg.the-hub.net':'new',
                          'http://kingscross.the-hub.net':'new',
                          'http://milan.the-hub.net':'new',
                          'http://madrid.the-hub.net':'new',
                          'http://porto.the-hub.net':'new',
                          'http://rotterdam.the-hub.net':'new',
                          'http://sanfrancisco.the-hub.net':'new',
                          'http://saopaulo.the-hub.net':'new',
                          'http://southbank.the-hub.net':'new',
                          'http://stockholm.the-hub.net':'new',
                          'http://telaviv.the-hub.net':'new',
                          'http://toronto.the-hub.net':'new',
                          'http://vienna.the-hub.net':'new',
                          'http://members.socialinnovation.ca':'old',
                          'http://members.themonksyard.co.uk':'old',
                          'http://hubspacedev.the-hub.net':'new',
                          'http://localhost:8080':'new',
                          'http://members.the-hub.net':'old',
                          'http://test.the-hub.net':'new',
                          'http://test2.the-hub.net':'new',
                          'http://testregion.the-hub.net':'new'}
)

title = URLMappings({'http://amsterdam.the-hub.net': 'The Hub Amsterdam',
                     'http://atlanta.the-hub.net': 'The Hub Atlanta',
                     'http://barcelona.the-hub.net': 'The Hub Barcelona',
                     'http://bayarea.the-hub.net': 'The Hub Bay Area',
                     'http://bergen.the-hub.net': 'The Hub Bergen',
                     'http://berlin.the-hub.net': 'The Hub Berlin',
                     'http://berkeley.the-hub.net': 'The Hub Berkeley',
                     'http://bogota.the-hub.net':'The Hub Bogota',
                     'http://bombay.the-hub.net':'The Hub Bombay',
                     'http://bristol.the-hub.net':'The Hub Bristol',
                     'http://brussels.the-hub.net':'The Hub Brussels',
                     'http://cairo.the-hub.net':'The Hub Cairo',
                     'http://capetown.the-hub.net':'The Hub Cape Town',
                     'http://copenhagen.the-hub.net':'The Hub Copenhagen',
                     'http://durban.the-hub.net':'The Hub Durban',
                     'http://halifax.the-hub.net':'The Hub Halifax',
                     'http://helsinki.the-hub.net':'The Hub Helsinki',
                     'http://islington.the-hub.net':'The Hub Islington',
                     'http://johannesburg.the-hub.net':'The Hub Johannesburg',
                     'http://kabul.the-hub.net':"The Hub Kabul",
                     'http://kingscross.the-hub.net':"The Hub King's Cross",
                     'http://losangeles.the-hub.net':"The Hub Los Angeles",
                     'http://la.the-hub.net':"The Hub Los Angeles",
                     'http://madrid.the-hub.net':'The Hub Madrid',
                     'http://milan.the-hub.net':'The Hub Milan',
                     'http://minneapolis.the-hub.net':'The Hub Minneapolis',
                     'http://newyork.the-hub.net':'The Hub New York',
                     'http://porto.the-hub.net':'The Hub Porto',
                     'http://prague.the-hub.net':'The Hub Prague',
                     'http://oaxaca.the-hub.net':'The Hub Oaxaca',
                     'http://riga.the-hub.net':'The Hub Riga',
                     'http://rotterdam.the-hub.net':'The Hub Rotterdam',
                     'http://shop.rotterdam.the-hub.net':'Hub Shop - Rotterdam',
                     'http://saopaulo.the-hub.net':'The Hub Sao Paulo',
                     'http://sanfrancisco.the-hub.net':'The Hub San Francisco',
                     'http://southbank.the-hub.net':'The Hub South Bank',
                     'http://stockholm.the-hub.net':'The Hub Stockholm',
                     'http://telaviv.the-hub.net':'The Hub Telaviv',
                     'http://vienna.the-hub.net':'The Hub Vienna',
                     'http://washintondc.the-hub.net':'The Hub Washington DC',
                     'http://dc.the-hub.net':'The Hub Washington DC',
                     'http://toronto.the-hub.net':'Centre for Social Innovation',
                     'http://members.socialinnovation.ca':'Centre for Social Innovation',
                     'http://members.themonksyard.co.uk':'The Monks Yard',
                     'http://localhost:8080':'The Hub',
                     'http://hubspacedev.the-hub.net':'The Hub',
                     'http://members.the-hub.net':'The Hub',
                     'http://test.the-hub.net':'The Hub',
                     'http://test2.the-hub.net':'The Hub',
                     'http://testregion.the-hub.net':'The Hub',}
)

site_folders = URLMappings({'http://localhost:8080':'site_templates.hubspace.',
                            'http://members.socialinnovation.ca':'site_templates.toronto.',
                            'http://toronto.the-hub.net':'site_templates.toronto.'})

site_default_lang = URLMappings({'http://localhost:8080':'en',
                                 'http://amsterdam.the-hub.net':'nl',
                                 'http://barcelona.the-hub.net':'es',
                                 'http://bergen.the-hub.net':'no',
                                 'http://berlin.the-hub.net':'de',
                                 'http://bogota.the-hub.net':'es',
                                 'http://copenhagen.the-hub.net':'en',
                                 'http://helsinki.the-hub.net':'fi',
                                 'http://madrid.the-hub.net':'es',
                                 'http://milan.the-hub.net':'it',
                                 'http://oaxaca.the-hub.net':'es',
                                 'http://porto.the-hub.net':'pt',
                                 'http://prague.the-hub.net':'cs',
                                 'http://rotterdam.the-hub.net':'nl',
                                 'http://shop.rotterdam.the-hub.net':'nl',
                                 'http://riga.the-hub.net':'lv',
                                 'http://saopaulo.the-hub.net':'pt',
                                 'http://stockholm.the-hub.net':'sv'})


analytics_no = URLMappings({'http://localhost:8080':None,
                            'http://the-hub.net':"1",
                            'http://wwww.the-hub.net':"1",
                            'http://islington.the-hub.net':"2"})



